In [1]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("book1-100k.csv")
data

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,652,4:556485,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,2:25317,5:1546466,NaN,3:159960
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,870,4:604283,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,2:37005,5:1493113,0439358078,3:211781
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,1:108202,309,4:1513191,total:6587388,1,11,Scholastic Inc,75911,2003,eng,J.K. Rowling,4.47,2:130310,5:4268227,NaN,3:567458
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,352,4:706082,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,2:49353,5:1504505,0439554896,3:288821
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,435,4:630534,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,2:24849,5:1749958,043965548X,3:194848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58287,99992,The Best American Science and Nature Writing 2000,1:2,265,4:58,total:164,26,10,Mariner Books,7,2000,NaN,David Quammen,3.99,2:8,5:58,0618082956,3:38
58288,99993,The Best American Science and Nature Writing 2002,1:0,336,4:33,total:87,15,10,Mariner Books,7,2002,NaN,Natalie Angier,4.11,2:2,5:33,0618134786,3:19
58289,99996,Hunting and Home in the Southern Heartland: Th...,1:0,263,4:3,total:10,1,4,University of South Carolina Press,0,1992,NaN,Archibald Hamilton Rutledge,4.30,2:0,5:5,0872498220,3:2
58290,99997,The Best American Science Writing 2004,1:2,288,4:49,total:102,14,9,Ecco,5,2004,NaN,Dava Sobel,3.86,2:3,5:23,0060726407,3:25
58291,99999,The Best American Sex Writing 2004,1:1,336,4:3,total:11,6,12,Running Press,3,2004,NaN,Daniel O'Connor,3.09,2:2,5:1,1560255986,3:4

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58292 entries, 0 to 58291
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               58292 non-null  int64
 1   Name             58292 non-null  object
 2   RatingDist1      58292 non-null  object
 3   pagesNumber      58292 non-null  int64
 4   RatingDist4      58292 non-null  object
 5   RatingDistTotal  58292 non-null  object
 6   PublishMonth     58292 non-null  int64
 7   PublishDay       58292 non-null  int64
 8   Publisher        57798 non-null  object
 9   CountsOfReview   58292 non-null  int64
 10  PublishYear      58292 non-null  int64
 11  Language         20294 non-null  object
 12  Authors          58292 non-null  object
 13  Rating           58292 non-null  float64
 14  RatingDist2      58292 non-null  object
 15  RatingDist5      58292 non-null  object
 16  ISBN             57746 non-null  object
 17  RatingDist3      58292 non-null  object
dtypes: float64(1), int64(6), object(11)
memory usage: 8.0+ MB

In [6]:
data.isnull().sum()

Id                     0
Name                   0
RatingDist1            0
pagesNumber            0
RatingDist4            0
RatingDistTotal        0
PublishMonth           0
PublishDay             0
Publisher            494
CountsOfReview         0
PublishYear            0
Language           37998
Authors                0
Rating                 0
RatingDist2            0
RatingDist5            0
ISBN                 546
RatingDist3            0
dtype: int64

In [7]:
data.dropna(axis=0,inplace=True)

In [8]:
data

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,870,4:604283,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,2:37005,5:1493113,0439358078,3:211781
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,352,4:706082,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,2:49353,5:1504505,0439554896,3:288821
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,435,4:630534,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,2:24849,5:1749958,043965548X,3:194848
6,8,"Harry Potter Boxed Set, Books 1-5 (Harry Potte...",1:402,2690,4:4650,total:43968,13,9,Scholastic,166,2004,eng,J.K. Rowling,4.78,2:283,5:37432,0439682584,3:1201
7,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",1:0,152,4:7,total:28,26,4,Nimble Books,1,2005,en-US,W. Frederick Zimmerman,3.79,2:5,5:10,0976540606,3:6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58260,99958,Thomas Paine and the Promise of America (Oxfor...,1:6,336,4:87,total:265,25,7,Hill and Wang,31,2006,eng,Harvey J. Kaye,3.91,2:13,5:89,0809093448,3:70
58262,99962,Common Sense and Other Writings,1:207,432,4:3602,total:11162,1,11,Barnes Noble Classics,2,2005,eng,Thomas Paine,3.91,2:722,5:3863,1593083769,3:2768
58265,99965,Faith of My Fathers: A Family Memoir,1:52,368,4:1471,total:3666,22,8,William Morrow Paperbacks,288,2000,eng,John McCain,3.86,2:209,5:1004,0060957867,3:930
58280,99985,Science Fiction: The Best of 2001,1:1,0,4:6,total:25,1,8,Fantastic Audio,0,2002,eng,Robert Silverberg,3.48,2:2,5:5,157453503X,3:11
58281,99986,Nebula Awards Showcase 2001,1:0,272,4:20,total:51,26,4,Mariner Books,5,2001,eng,Robert Silverberg,3.82,2:2,5:12,0156013355,3:17

In [9]:
data['Name'].values

array(['Harry Potter and the Order of the Phoenix (Harry Potter, #5)',
       'Harry Potter and the Chamber of Secrets (Harry Potter, #2)',
       'Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)', ...,
       'Faith of My Fathers: A Family Memoir',
       'Science Fiction: The Best of 2001', 'Nebula Awards Showcase 2001'],
      dtype=object)